---

- name: Install apache packages
  ansible.builtin.package:
    name: "{{ apache_packages }}"
    state: present

- name: Start the apache service
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
