---

- name: Define defaults to use based on OS type
  ansible.builtin.set_fact:
    defaults: "{{ lookup('first_found', params) | basename }}"
  vars:
    params:
      files:
        - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "defaults/{{ ansible_distribution }}.yml"
        - "defaults/family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "defaults/family-{{ ansible_os_family }}.yml"
        - "defaults/main.yml"

- name: Show defaults selected
  ansible.builtin.debug:
    var: defaults

- name: Execute role again using selected defaults
  ansible.builtin.include_role:
    name: "{{ role_name }}"
    defaults_from: "{{ defaults }}"
    tasks_from: "main1.yml"
