---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "vars"

- name: Install all apache packages
  package:
    name: "{{ apache_packages }}"
    state: present

- name: Activate SSL using a2enmod
  command: a2enmod ssl
  register: _a2enmod_ssl
  changed_when: "_a2enmod_ssl.stdout is not search('Module ssl already enabled')"
  when: ansible_os_family == 'Debian'

- name: Configure SSL keys & certificates
  replace:
    path: '{{ apache_ssl_conf }}'
    regexp: '^(#)?{{ item.key }} .*'
    replace: '{{ item.key }} {{ item.value }}'
  loop: "{{ apache_ssl_settings | dict2items }}"
  when: apache_ssl|bool
  notify: Restart apache

- name: Configure vhosts
  include_tasks: vhost.yml
  loop: "{{ apache_vhosts }}"
  loop_control:
    label:
      - "{{ item.vhost }}"

- name: Start the apache service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Set boolean so we know which webserver is used
  set_fact:
    webserver_in_use: apache
