---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "vars"

# Install apache
- name: Install apache
  include_tasks: install.yml

# Config apache
- name: Config apache
  include_tasks: config.yml

# vhosts
- name: Configure vhosts
  include_tasks: vhost.yml
  loop: "{{ apache_vhosts }}"
  loop_control:
    label:
      - "{{ item.vhost }}"

- name: Set some variables for other roles to use
  set_fact:
    webserver_in_use: apache
    webserver_service: "{{ apache_service }}"
    webserver_user: "{{ apache_user }}"
    webserver_group: "{{ apache_group }}"
