---

- name: Define vhost specific variables
  ansible.builtin.set_fact:
    vhost_docroot: "{{ item.docroot | default(apache_vhostdir + '/' + item.vhost + '/public_html') }}"
    vhost_sslpath: "{{ item.sslpath | default(apache_vhostdir + '/' + item.vhost + '/ssl') }}"
    vhost_logpath: "{{ item.logpath | default(apache_vhostdir + '/' + item.vhost + '/log') }}"
    vhost_errorlog: "{{ item.errorlog | default(apache_vhostdir + '/' + item.vhost + '/log/error.log') }}"
    vhost_customlog: "{{ item.customlog | default(apache_vhostdir + '/' + item.vhost + '/log/access.log') }}"

- name: Distribute vhost configuration
  ansible.builtin.template:
    src: "templates/{{ item.template }}"
    dest: "{{ apache_conf_dir }}/{{ item.vhost }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart apache

- name: Activate vhosts
  ansible.builtin.file:
    src: "{{ apache_conf_dir }}/{{ item.vhost }}.conf"
    dest: /etc/apache2/sites-enabled/{{ item.vhost }}.conf
    owner: root
    group: root
    state: link
  notify: Restart apache
  when: ansible_os_family == 'Debian'

- name: Create 'public_html' directory
  ansible.builtin.file:
    path: "{{ vhost_docroot }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  notify: Restart apache

- name: Create 'ssl' directory
  ansible.builtin.file:
    path: "{{ vhost_sslpath }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0750"
  notify: Restart apache

- name: Create 'log' directory
  ansible.builtin.file:
    path: "{{ vhost_logpath }}"
    state: directory
    owner: "root"
    group: "{{ item.group | default('root') }}"
    mode: "0750"
  notify: Restart apache

- name: Copy SSL keys
  when: item.ssl_copy is defined and item.ssl_copy | bool
  block:

    - name: Provision SSL private key
      ansible.builtin.copy:
        src: "{{ item.ssl_key }}"
        dest: "{{ vhost_sslpath }}/{{ item.vhost }}.key"
        owner: root
        group: root
        mode: "0600"
        remote_src: "{{ True if item.ssl_key is search('^/') else False }}"
      notify: Restart apache
      when: item.ssl_key is defined

    - name: Provision SSL certificates
      ansible.builtin.copy:
        src: "{{ item.ssl_crt }}"
        dest: "{{ vhost_sslpath }}/{{ item.vhost }}.crt"
        owner: root
        group: root
        mode: "0644"
        remote_src: "{{ True if item.ssl_crt is search('^/') else False }}"
      notify: Restart apache
      when: item.ssl_crt is defined

    - name: Provision SSL certificate chain
      ansible.builtin.copy:
        src: "{{ item.ssl_chain }}"
        dest: "{{ vhost_sslpath }}/{{ item.vhost }}.chain"
        owner: root
        group: root
        mode: "0644"
        remote_src: "{{ True if item.ssl_chain is search('^/') else False }}"
      notify: Restart apache
      when: item.ssl_chain is defined

- name: Create test index.html
  ansible.builtin.template:
    src: "{{ item.index_html_template | default('templates/vhost.index.html.j2') }}"
    dest: "{{ vhost_docroot }}/index.html"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "0644"
    force: no
  # when: apache_index_html is defined and apache_index_html|bool
  when: item.index_html is defined and item.index_html | bool
