---

- name: Distribute vhost configuration
  template:
    src: "templates/{{ item.template }}"
    dest: "{{ apache_conf_dir }}/{{ item.vhost }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart apache

- name: Activate vhosts
  file:
    src: "{{ apache_conf_dir }}/{{ item.vhost }}.conf"
    dest: /etc/apache2/sites-enabled/{{ item.vhost }}.conf
    owner: root
    group: root
    state: link
  notify: Restart apache
  when: ansible_os_family == 'Debian'
 
- name: Create vhost directories
  file:
    path: "{{ item.docroot | default(apache_vhostdir+'/'+item.vhost+'/public_html') }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  notify: Restart apache

- name: Create vhosts log directory
  file:
    path: "{{ item.errorlog | default(apache_vhostdir+'/'+item.vhost+'/log/error.log') | dirname }}"
    state: directory
    mode: "0755"

- name: Create test index.html
  template:
    src: templates/vhost.index.html.j2
    dest: "{{ apache_vhost_dir | default(apache_vhostdir + '/' + item.vhost) }}/public_html/index.html"
    mode: "0644"
    force: no
  when: apache_index_html is defined and apache_index_html|bool
