---

- name: Converge
  hosts: all
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Create 'remote_tmp'
      file:
        path: /root/.ansible/tmp
        state: directory
        mode: "0700"
  roles:
    - openssl
  tasks:
    - name: Include role 'ansible-role-apache'
      include_role:
        name: ansible-role-apache
